# Generated by Django 4.2.7 on 2024-04-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='Не указан', max_length=254),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='Не указан', max_length=20),
        ),
        migrations.AddField(
            model_name='trainer',
            name='phone',
            field=models.CharField(default='Не указан', max_length=20),
        ),
    ]
