# Generated by Django 4.2.7 on 2024-03-05 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(upload_to='avatars'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthDate',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
        ),
    ]
