# Generated by Django 4.2.7 on 2024-02-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporttype',
            name='trainers',
        ),
        migrations.AddField(
            model_name='trainer',
            name='sport_types',
            field=models.ManyToManyField(to='trainers.sporttype'),
        ),
        migrations.AlterField(
            model_name='abonement',
            name='sport',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trainers.sporttype'),
        ),
        migrations.AlterField(
            model_name='team',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='trainers.trainer'),
        ),
    ]
