# Generated by Django 4.2.5 on 2023-10-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='days_left',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='date_of_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
