# Generated by Django 4.2.7 on 2024-02-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_remove_sporttype_trainers_trainer_sport_types_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='sport_types',
        ),
    ]
