# Generated by Django 4.2.7 on 2024-04-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_alter_client_avatar_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(upload_to='avatars'),
        ),
    ]
