# Generated by Django 4.2.7 on 2024-04-04 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_remove_trainer_sport_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.activity'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.client'),
        ),
        migrations.AlterField(
            model_name='presence',
            name='presence',
            field=models.BooleanField(default=False),
        ),
    ]
