# Generated by Django 4.2.7 on 2024-04-26 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_alter_client_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.purchasehistory'),
        ),
    ]
